In [1]:
import pandas as pd
import numpy as np

In [2]:
detail1=pd.read_excel('./meal_order_detail.xlsx','meal_order_detail1')
detail1

detail_id  order_id  dishes_id  logicprn_name  parent_class_name  \
0          2956       417     610062            NaN                NaN   
1          2958       417     609957            NaN                NaN   
2          2961       417     609950            NaN                NaN   
3          2966       417     610038            NaN                NaN   
4          2968       417     610003            NaN                NaN   
...         ...       ...        ...            ...                ...   
2774       6750       774     610011            NaN                NaN   
2775       6742       774     609996            NaN                NaN   
2776       6756       774     609949            NaN                NaN   
2777       6763       774     610014            NaN                NaN   
2778       6764       774     610017            NaN                NaN   

            dishes_name  itemis_add  counts  amounts  cost  \
0                  蒜蓉生蚝           0       1       49   NaN   
1     蒙古烤羊腿\r\n\r\n\r\n           0       1       48   NaN   
2                  大蒜苋菜           0       1       30   NaN   
3                 芝麻烤紫菜           0       1       25   NaN   
4                   蒜香包           0       1       13   NaN   
...                 ...         ...     ...      ...   ...   
2774              白饭/大碗           0       1       10   NaN   
2775                牛尾汤           0       1       40   NaN   
2776             意文柠檬汁            0       1       13   NaN   
2777               金玉良缘           0       1       30   NaN   
2778               酸辣藕丁           0       1       33   NaN   

        place_order_time  discount_amt  discount_reason  kick_back  \
0    2016-08-01 11:05:36           NaN              NaN        NaN   
1    2016-08-01 11:07:07           NaN              NaN        NaN   
2    2016-08-01 11:07:40           NaN              NaN        NaN   
3    2016-08-01 11:11:11           NaN              NaN        NaN   
4    2016-08-01 11:11:30           NaN              NaN        NaN   
...                  ...           ...              ...        ...   
2774 2016-08-10 21:56:24           NaN              NaN        NaN   
2775 2016-08-10 21:56:48           NaN              NaN        NaN   
2776 2016-08-10 22:01:52           NaN              NaN        NaN   
2777 2016-08-10 22:03:58           NaN              NaN        NaN   
2778 2016-08-10 22:04:30           NaN              NaN        NaN   

      add_inprice  add_info  bar_code      picture_file  emp_id  
0               0       NaN       NaN  caipu/104001.jpg    1442  
1               0       NaN       NaN  caipu/202003.jpg    1442  
2               0       NaN       NaN  caipu/303001.jpg    1442  
3               0       NaN       NaN  caipu/105002.jpg    1442  
4               0       NaN       NaN  caipu/503002.jpg    1442  
...           ...       ...       ...               ...     ...  
2774            0       NaN       NaN  caipu/601005.jpg    1138  
2775            0       NaN       NaN  caipu/201006.jpg    1138  
2776            0       NaN       NaN  caipu/404005.jpg    1138  
2777            0       NaN       NaN  caipu/302003.jpg    1138  
2778            0       NaN       NaN  caipu/302006.jpg    1138  

[2779 rows x 19 columns]

In [3]:
# 最大最小标准化
def MinMaxScale(data):
    return (data-data.min())/(data.max()-data.min())
a=MinMaxScale(detail1['counts'])
b=MinMaxScale(detail1['amounts'])
pd.concat([a,b],axis=1)

counts   amounts
0        0.0  0.271186
1        0.0  0.265537
2        0.0  0.163842
3        0.0  0.135593
4        0.0  0.067797
...      ...       ...
2774     0.0  0.050847
2775     0.0  0.220339
2776     0.0  0.067797
2777     0.0  0.163842
2778     0.0  0.180791

[2779 rows x 2 columns]

## 标准化数据

In [4]:
# Z-Score（标准差）标准化
def StandardScale(data):
    return (data-data.mean())/data.std()
a=StandardScale(detail1['counts'])
b=StandardScale(detail1['amounts'])
pd.concat([a,b],axis=1)

counts   amounts
0    -0.177784  0.099510
1    -0.177784  0.072343
2    -0.177784 -0.416674
3    -0.177784 -0.552512
4    -0.177784 -0.878523
...        ...       ...
2774 -0.177784 -0.960026
2775 -0.177784 -0.144998
2776 -0.177784 -0.878523
2777 -0.177784 -0.416674
2778 -0.177784 -0.335171

[2779 rows x 2 columns]

In [5]:
# 小数定标标准化
def DecimalScale(data):
    return data/10**(np.ceil(np.log10(data.abs().max())))
a=DecimalScale(detail1['counts'])
b=DecimalScale(detail1['amounts'])
pd.concat([a,b],axis=1)

counts  amounts
0        0.1    0.049
1        0.1    0.048
2        0.1    0.030
3        0.1    0.025
4        0.1    0.013
...      ...      ...
2774     0.1    0.010
2775     0.1    0.040
2776     0.1    0.013
2777     0.1    0.030
2778     0.1    0.033

[2779 rows x 2 columns]

In [6]:
# Log变换
def LogScale(data):
    return np.log10(data)
a=LogScale(detail1['counts'])
b=LogScale(detail1['amounts'])
pd.concat([a,b],axis=1)

counts   amounts
0        0.0  1.690196
1        0.0  1.681241
2        0.0  1.477121
3        0.0  1.397940
4        0.0  1.113943
...      ...       ...
2774     0.0  1.000000
2775     0.0  1.602060
2776     0.0  1.113943
2777     0.0  1.477121
2778     0.0  1.518514

[2779 rows x 2 columns]

In [7]:
from sklearn import preprocessing

min_max_scaler=preprocessing.MinMaxScaler()
min_max_scaler.fit_transform(detail1[['counts','amounts']])

array([[0.        , 0.27118644],
       [0.        , 0.26553672],
       [0.        , 0.16384181],
       ...,
       [0.        , 0.06779661],
       [0.        , 0.16384181],
       [0.        , 0.18079096]])

In [8]:
min_max_scaler=preprocessing.MinMaxScaler()
min_max_scaler=min_max_scaler.fit(detail1[['counts','amounts']])
min_max_scaler.transform([[2,30]])

array([[0.11111111, 0.16384181]])

In [9]:
standard_scaler=preprocessing.StandardScaler()
standard_scaler.fit_transform(detail1[['counts','amounts']])

array([[-0.17781606,  0.09952817],
       [-0.17781606,  0.07235568],
       [-0.17781606, -0.41674915],
       ...,
       [-0.17781606, -0.87868148],
       [-0.17781606, -0.41674915],
       [-0.17781606, -0.33523168]])

In [10]:
sales=pd.read_excel('./超市营业额2.xlsx')
sales

工号  姓名          日期           时段     交易额    柜台
0    1001  张三  2019-03-01   9：00-14：00  1664.0   化妆品
1    1002  李四  2019-03-01  14：00-21：00   954.0   化妆品
2    1003  王五  2019-03-01   9：00-14：00  1407.0    食品
3    1004  赵六  2019-03-01  14：00-21：00  1320.0    食品
4    1005  周七  2019-03-01   9：00-14：00   994.0   日用品
..    ...  ..         ...          ...     ...   ...
244  1002  李四  2019-03-31  14：00-21：00   859.0  蔬菜水果
245  1004  赵六  2019-03-31   9：00-14：00  1668.0   日用品
246  1004  赵六  2019-03-31  14：00-21：00  1722.0   日用品
247  1003  王五  2019-03-31   9：00-14：00  1274.0    食品
248  1006  钱八  2019-03-31  14：00-21：00   812.0    食品

[249 rows x 6 columns]

In [11]:
sales['柜台'].unique()

array(['化妆品', '食品', '日用品', '蔬菜水果'], dtype=object)

In [12]:
sales['柜台'].value_counts()

蔬菜水果    63
日用品     62
化妆品     62
食品      62
Name: 柜台, dtype: int64

## 数值映射

In [13]:
# 第一种方法
sales=pd.read_excel('./超市营业额2.xlsx')
sales['柜台'].replace(['化妆品', '食品', '日用品', '蔬菜水果'],range(4),inplace=True)

In [14]:
# 第二种方法
sales=pd.read_excel('./超市营业额2.xlsx')
sales['柜台']=sales['柜台'].map({'化妆品':0,'食品':1,'日用品':2,'蔬菜水果':3})
sales

工号  姓名          日期           时段     交易额  柜台
0    1001  张三  2019-03-01   9：00-14：00  1664.0   0
1    1002  李四  2019-03-01  14：00-21：00   954.0   0
2    1003  王五  2019-03-01   9：00-14：00  1407.0   1
3    1004  赵六  2019-03-01  14：00-21：00  1320.0   1
4    1005  周七  2019-03-01   9：00-14：00   994.0   2
..    ...  ..         ...          ...     ...  ..
244  1002  李四  2019-03-31  14：00-21：00   859.0   3
245  1004  赵六  2019-03-31   9：00-14：00  1668.0   2
246  1004  赵六  2019-03-31  14：00-21：00  1722.0   2
247  1003  王五  2019-03-31   9：00-14：00  1274.0   1
248  1006  钱八  2019-03-31  14：00-21：00   812.0   1

[249 rows x 6 columns]

In [15]:
# 第三种方法
sales=pd.read_excel('./超市营业额2.xlsx')
labels,uniques=pd.factorize(sales['柜台'])
print(labels)
print(uniques)

sales['柜台']=labels
sales

[0 0 1 1 2 2 3 3 0 0 1 1 2 2 3 3 0 0 1 1 2 2 3 3 0 0 1 1 2 2 3 3 0 0 1 1 2
 2 3 3 0 0 1 1 2 2 3 3 0 0 1 1 2 2 3 3 0 0 1 1 2 2 3 3 0 0 1 1 2 2 3 3 0 0
 1 1 2 2 3 3 2 2 1 1 0 0 3 3 2 2 1 1 0 0 3 3 2 2 1 1 0 0 3 3 3 2 2 1 1 0 0
 3 3 2 2 1 1 0 0 3 3 2 2 1 1 0 0 3 3 2 2 3 3 0 0 1 1 0 0 3 3 2 2 1 1 0 0 3
 3 2 2 1 1 0 0 3 3 2 2 1 1 0 0 3 3 2 2 1 1 0 0 3 3 2 2 1 1 0 0 3 3 2 2 1 1
 0 0 3 3 2 2 1 1 0 0 3 3 2 2 1 1 0 0 3 3 2 2 1 1 0 0 3 3 2 2 1 1 0 0 3 3 2
 2 1 1 0 0 3 3 2 2 1 1 0 0 3 3 2 2 1 1 0 0 3 3 2 2 1 1]
Index(['化妆品', '食品', '日用品', '蔬菜水果'], dtype='object')


工号  姓名          日期           时段     交易额  柜台
0    1001  张三  2019-03-01   9：00-14：00  1664.0   0
1    1002  李四  2019-03-01  14：00-21：00   954.0   0
2    1003  王五  2019-03-01   9：00-14：00  1407.0   1
3    1004  赵六  2019-03-01  14：00-21：00  1320.0   1
4    1005  周七  2019-03-01   9：00-14：00   994.0   2
..    ...  ..         ...          ...     ...  ..
244  1002  李四  2019-03-31  14：00-21：00   859.0   3
245  1004  赵六  2019-03-31   9：00-14：00  1668.0   2
246  1004  赵六  2019-03-31  14：00-21：00  1722.0   2
247  1003  王五  2019-03-31   9：00-14：00  1274.0   1
248  1006  钱八  2019-03-31  14：00-21：00   812.0   1

[249 rows x 6 columns]

In [16]:
# 第四种方法
sales=pd.read_excel('./超市营业额2.xlsx')
label_encoder=preprocessing.LabelEncoder()
sales['柜台']=label_encoder.fit_transform(sales['柜台'])
sales

工号  姓名          日期           时段     交易额  柜台
0    1001  张三  2019-03-01   9：00-14：00  1664.0   0
1    1002  李四  2019-03-01  14：00-21：00   954.0   0
2    1003  王五  2019-03-01   9：00-14：00  1407.0   3
3    1004  赵六  2019-03-01  14：00-21：00  1320.0   3
4    1005  周七  2019-03-01   9：00-14：00   994.0   1
..    ...  ..         ...          ...     ...  ..
244  1002  李四  2019-03-31  14：00-21：00   859.0   2
245  1004  赵六  2019-03-31   9：00-14：00  1668.0   1
246  1004  赵六  2019-03-31  14：00-21：00  1722.0   1
247  1003  王五  2019-03-31   9：00-14：00  1274.0   3
248  1006  钱八  2019-03-31  14：00-21：00   812.0   3

[249 rows x 6 columns]

In [17]:
sales=pd.read_excel('./超市营业额2.xlsx')
pd.get_dummies(sales['柜台'])

化妆品  日用品  蔬菜水果  食品
0      1    0     0   0
1      1    0     0   0
2      0    0     0   1
3      0    0     0   1
4      0    1     0   0
..   ...  ...   ...  ..
244    0    0     1   0
245    0    1     0   0
246    0    1     0   0
247    0    0     0   1
248    0    0     0   1

[249 rows x 4 columns]

In [18]:
one_hot_encoder=preprocessing.OneHotEncoder(categories='auto')
one_hot_encoder.fit_transform(pd.DataFrame(sales['柜台']))

<249x4 sparse matrix of type '<class 'numpy.float64'>'
	with 249 stored elements in Compressed Sparse Row format>