In [1]:
import pandas as pd

In [4]:
a=pd.Series([9,8,7,6])

In [5]:
a

0    9
1    8
2    7
3    6
dtype: int64

In [8]:
b=pd.Series([9,8,7,6],index=['a','b','c','d'])

In [9]:
b

a    9
b    8
c    7
d    6
dtype: int64

In [10]:
s=pd.Series(25,index=['a','b','c','d'])

In [11]:
s

a    25
b    25
c    25
d    25
dtype: int64

In [12]:
d=pd.Series({'a':9,'b':8,'c':7})
d

a    9
b    8
c    7
dtype: int64

In [13]:
e=pd.Series(d,index=['c','a','b','d'])

In [14]:
e

c    7.0
a    9.0
b    8.0
d    NaN
dtype: float64

In [15]:
import numpy as np

In [16]:
n=pd.Series(np.arange(5))
n

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [17]:
b.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [18]:
b.values

array([9, 8, 7, 6], dtype=int64)

In [19]:
b['b']

8

In [20]:
b[1]

8

In [26]:
b[['c','d']]

c    7
d    6
dtype: int64

In [27]:
b[3]

6

In [28]:
b

a    9
b    8
c    7
d    6
dtype: int64

In [29]:
b[:3]

a    9
b    8
c    7
dtype: int64

In [30]:
b[3]

6

In [32]:
b[b>b.median()]

a    9
b    8
dtype: int64

In [33]:
np.exp(b)

a    8103.083928
b    2980.957987
c    1096.633158
d     403.428793
dtype: float64

In [34]:
'c' in b

True

In [35]:
0 in b

False

In [36]:
b.get('f',100)

100

In [37]:
b.get('a')

9

In [38]:
b.get('a',100)

9

In [39]:
a

0    9
1    8
2    7
3    6
dtype: int64

In [40]:
a=pd.Series([1,2,3],index=['c','d','e'])

In [41]:
a+b

a    NaN
b    NaN
c    8.0
d    8.0
e    NaN
dtype: float64

In [42]:
b.name

In [43]:
b.name='Series对象'

In [44]:
b.index_name='aa'

In [45]:
b

a    9
b    8
c    7
d    6
Name: Series对象, dtype: int64

In [46]:
b.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [48]:
b.index_name

'aa'

In [50]:
a=pd.Series(np.array([27, 27,28,29,30,30,np.nan]))
a

0    27.0
1    27.0
2    28.0
3    29.0
4    30.0
5    30.0
6     NaN
dtype: float64

In [51]:
a.index

RangeIndex(start=0, stop=7, step=1)

In [52]:
a.values

array([27., 27., 28., 29., 30., 30., nan])

In [53]:
len(a)

7

In [55]:
a.shape

(7,)

In [56]:
a.count()

6

In [57]:
a.unique()

array([27., 28., 29., 30., nan])

In [58]:
a.value_counts()

30.0    2
27.0    2
29.0    1
28.0    1
dtype: int64

In [59]:
d=pd.DataFrame(np.arange(10).reshape(2,5))
d

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

In [60]:
dt={'one':pd.Series([1,2,3],index=['a','b','c']),'two':pd.Series([9,8,7,6],index=['a','b','c','d'])}

In [61]:
d=pd.DataFrame(dt)
d

one  two
a  1.0    9
b  2.0    8
c  3.0    7
d  NaN    6

In [63]:
pd.DataFrame(dt,index=['b','c','d'],columns=['two','ccc'])

two  ccc
b    8  NaN
c    7  NaN
d    6  NaN

In [64]:
dl={'one':[1,2,3,4],'two':[9,8,7,6]}

In [65]:
d=pd.DataFrame(dl,index=['a','b','c','d'])

In [66]:
d

one  two
a    1    9
b    2    8
c    3    7
d    4    6

In [67]:
dl={
    '城市':['bj','sh','gz'],
    '环比':[101.5,0.1,0.2]
}

In [79]:
d=pd.DataFrame(dl,index=['c1','c2','c3'])

In [80]:
d

城市     环比
c1  bj  101.5
c2  sh    0.1
c3  gz    0.2

In [81]:
d.values

array([['bj', 101.5],
       ['sh', 0.1],
       ['gz', 0.2]], dtype=object)

In [82]:
d['城市']

c1    bj
c2    sh
c3    gz
Name: 城市, dtype: object

In [88]:
d

城市     环比
c1  bj  101.5
c2  sh    0.1
c3  gz    0.2

In [90]:
t=[[1,1,1],[2,2,2],[3,3,3]]

In [91]:
df=pd.DataFrame(t)

In [92]:
df

0  1  2
0  1  1  1
1  2  2  2
2  3  3  3

In [93]:
df.head(2)

0  1  2
0  1  1  1
1  2  2  2

In [94]:
df.tail(2)

0  1  2
1  2  2  2
2  3  3  3

In [95]:
df1=pd.DataFrame(np.arange(100).reshape(50,2))

In [97]:
df1.head()

0  1
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9